#!/usr/bin/env bash
set -euo pipefail

# Build pages/ for GitHub Pages deployment.
# Run this before committing pages/ changes.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
TML_DIR="$PROJECT_DIR/../sw-cor24-macrolisp"

# Resolve and PIN tc24r to the blessed sw-cor24-x-tinyc compiler. The committed
# asm/*.s must only ever be regenerated by this exact compiler — a different
# tc24r silently drifts the output, which is the defect this re-baseline fixes.
# So we FAIL LOUDLY rather than fall back to an unpinned PATH binary of unknown
# provenance. Resolution order: explicit $TC24R, then the sibling release build,
# then PATH; whatever resolves must match the blessed md5.
BLESSED_TC24R_MD5="c539a57b6ec33397120a00990d8a2876"
TC24R="${TC24R:-$PROJECT_DIR/../sw-cor24-x-tinyc/components/cli/target/release/tc24r}"
if [[ ! -x "$TC24R" ]] && command -v tc24r >/dev/null 2>&1; then
  TC24R="$(command -v tc24r)"
fi
if [[ ! -x "$TC24R" ]]; then
  echo "error: tc24r not found (looked at \$TC24R / ../sw-cor24-x-tinyc / PATH)." >&2
  echo "       Provide the blessed sw-cor24-x-tinyc tc24r (md5 $BLESSED_TC24R_MD5)." >&2
  exit 1
fi
got_md5="$(md5sum "$TC24R" | cut -d' ' -f1)"
if [[ "$got_md5" != "$BLESSED_TC24R_MD5" ]]; then
  echo "error: tc24r at $TC24R is NOT the blessed compiler." >&2
  echo "       expected md5 $BLESSED_TC24R_MD5" >&2
  echo "       got      md5 $got_md5" >&2
  echo "       Regenerating asm with an unpinned tc24r would silently drift the" >&2
  echo "       committed output. Set \$TC24R to the blessed sw-cor24-x-tinyc build." >&2
  exit 1
fi
echo "Using blessed tc24r: $TC24R (md5 $got_md5)"

# 1. Recompile the REPL variants that config.rs actually consumes. Standard maps
#    to the snapshot-capable repl-snapshot.s — NOT repl-standard.s, which
#    config.rs never include_str!s. Regenerating the unused repl-standard.s while
#    skipping the consumed repl-snapshot.s was the snapshot-path gap.
echo "=== Compiling REPL variants ==="
for v in bare minimal snapshot full scheme; do
  echo "  repl-$v..."
  "$TC24R" "$TML_DIR/src/repl-$v.c" -I "$TML_DIR/src" -o "$PROJECT_DIR/asm/repl-$v.s"
done

# 1b. Regenerate the standard-tier heap snapshot. This is dcmls's upstream
#     artifact, so we RUN their migrated justfile recipe against the pinned
#     source (pinning tc24r to the blessed compiler resolved above) rather than
#     reimplement it here. Closes the other half of the snapshot-path gap.
echo "=== Regenerating standard.snap (upstream snapshot recipe) ==="
if ! command -v just >/dev/null 2>&1; then
  echo "error: 'just' not on PATH — needed to run the macrolisp snapshot recipe." >&2
  exit 1
fi
( cd "$TML_DIR" && just tc24r="$TC24R" snapshot )
cp "$TML_DIR/build/prelude.snap" "$PROJECT_DIR/snapshots/standard.snap"

# 2. Build WASM into dist/ (gitignored), then sync to pages/
#    rsync --exclude preserves .nojekyll in pages/ across rebuilds
echo "=== Building pages/ ==="
cd "$PROJECT_DIR"
mkdir -p pages
touch pages/.nojekyll
trunk build --release --public-url /web-sw-cor24-macrolisp/ -d dist
rsync -a --delete --exclude='.nojekyll' dist/ pages/

echo "=== Done ==="
echo "Pages built in: $PROJECT_DIR/pages/"
echo "To preview locally: ./scripts/serve.sh"
echo "To deploy: git add pages/ && git commit && git push"
