use crate::config::{PreludeTier, StackSize};

pub struct Demo {
    pub title: &'static str,
    pub description: &'static str,
    pub source: &'static str,
    pub prelude: PreludeTier,
    pub stack: StackSize,
}

/// Demos grouped by prelude tier, alphabetical within each group.
pub const DEMOS: &[Demo] = &[
    // ── Minimal prelude ──────────────────────────────────────
    Demo {
        title: "Tail-Call Optimization",
        description: "Constant-stack recursion: countdown, sum, fibonacci",
        source: include_str!("../../sw-cor24-macrolisp/demos/tco.l24"),
        prelude: PreludeTier::Minimal,
        stack: StackSize::EightKb,
    },
    // ── Standard prelude ─────────────────────────────────────
    Demo {
        title: "Blink LED",
        description: "Toggle LED D2 via memory-mapped I/O",
        source: include_str!("../../sw-cor24-macrolisp/demos/blink.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
    },
    Demo {
        title: "Bottles of Beer",
        description: "99 Bottles via macro + tail recursion (5 verses)",
        source: include_str!("../../sw-cor24-macrolisp/demos/bottles.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
    },
    Demo {
        title: "Bottles (Functional)",
        description: "99 Bottles via map/for-each — functional style",
        source: include_str!("../../sw-cor24-macrolisp/demos/bottles4.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
    },
    Demo {
        title: "Continuations",
        description: "catch/throw, call/ec, guard, dynamic-wind",
        source: include_str!("../../sw-cor24-macrolisp/demos/continuations.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
    },
    Demo {
        title: "Error Handling",
        description: "Runtime errors: type errors, div-by-zero, unbound symbols",
        source: include_str!("../../sw-cor24-macrolisp/demos/errors.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
    },
    Demo {
        title: "Fixed-Point Arithmetic",
        description: "Scaled integers for currency and measurement calculations",
        source: include_str!("../../sw-cor24-macrolisp/demos/fixedpoint.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
    },
    Demo {
        title: "Fuzzy Equality",
        description: "DSL macro: (if~= a ~= b +/- e then X else Y)",
        source: include_str!("../../sw-cor24-macrolisp/demos/fuzzy-eq.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
    },
    Demo {
        title: "Infix Syntax",
        description: "Binary and variadic infix arithmetic via macros",
        source: include_str!("../../sw-cor24-macrolisp/demos/infix.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
    },
    Demo {
        title: "Macros",
        description: "let, cond, and, or — core macro system",
        source: include_str!("../../sw-cor24-macrolisp/demos/macros.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
    },
    Demo {
        title: "Metaprogramming",
        description: "macroexpand, gensym, eval, symbol/string conversion",
        source: include_str!("../../sw-cor24-macrolisp/demos/metaprogramming.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
    },
    Demo {
        title: "Multi-body Forms",
        description: "Multi-body lambda, define, and defmacro",
        source: include_str!("../../sw-cor24-macrolisp/demos/multibody.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
    },
    Demo {
        title: "Multi-line Input",
        description: "Balanced-paren tracking across newlines",
        source: include_str!("../../sw-cor24-macrolisp/demos/multiline.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
    },
    Demo {
        title: "Mutation",
        description: "set!, counter closures, memoized fibonacci",
        source: include_str!("../../sw-cor24-macrolisp/demos/mutation.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
    },
    Demo {
        title: "Parameters",
        description: "make-parameter, parameterize — dynamic scoping",
        source: include_str!("../../sw-cor24-macrolisp/demos/parameters.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
    },
    Demo {
        title: "Percent Tolerance",
        description: "Hygienic macro: percentage-tolerance equality DSL",
        source: include_str!("../../sw-cor24-macrolisp/demos/percent-tol.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
    },
    Demo {
        title: "Power (Integer Exponent)",
        description: "N^E via tail-recursive accumulator; 22-bit fixnum wrap caveat",
        source: include_str!("../../sw-cor24-macrolisp/demos/power.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
    },
    Demo {
        title: "Quasiquote",
        description: "Template expansion with unquote and splicing",
        source: include_str!("../../sw-cor24-macrolisp/demos/quasiquote.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
    },
    Demo {
        title: "Restartable Conditions",
        description: "CL-style restartable conditions, map with recovery",
        source: include_str!("../../sw-cor24-macrolisp/demos/restarts.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
    },
    Demo {
        title: "String Formatting",
        description: "format with ~a interpolation, tables, error messages",
        source: include_str!("../../sw-cor24-macrolisp/demos/format.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
    },
    Demo {
        title: "Switch LED",
        description: "Mirror S2 switch to LED D2 in a polling loop",
        source: include_str!("../../sw-cor24-macrolisp/demos/switch-led.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
    },
    Demo {
        title: "Strings",
        description: "String type: length, append, ref, conversion",
        source: include_str!("../../sw-cor24-macrolisp/demos/strings.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
    },
    Demo {
        title: "Variadic Functions",
        description: "Rest parameters: (lambda args ...) and (lambda (a . rest) ...)",
        source: include_str!("../../sw-cor24-macrolisp/demos/variadic.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
    },
    // ── Full prelude ─────────────────────────────────────────
    Demo {
        title: "Anaphoric Macros",
        description: "Unhygienic macros: aif, awhen, aand with implicit 'it'",
        source: include_str!("../../sw-cor24-macrolisp/demos/anaphora.l24"),
        prelude: PreludeTier::Full,
        stack: StackSize::ThreeKb,
    },
    Demo {
        title: "Bottles (Trampoline)",
        description: "Full 99 via mutual-recursion trampoline",
        source: include_str!("../../sw-cor24-macrolisp/demos/bottles2.l24"),
        prelude: PreludeTier::Full,
        stack: StackSize::EightKb,
    },
    Demo {
        title: "Functional Toolkit",
        description: "fn?, compose, complement, every?, flatten, zip",
        source: include_str!("../../sw-cor24-macrolisp/demos/functional.l24"),
        prelude: PreludeTier::Full,
        stack: StackSize::ThreeKb,
    },
    Demo {
        title: "Iteration Patterns",
        description: "Named let, do loop, type dispatch with fn?",
        source: include_str!("../../sw-cor24-macrolisp/demos/iteration.l24"),
        prelude: PreludeTier::Full,
        stack: StackSize::ThreeKb,
    },
    Demo {
        title: "Lazy Sequences",
        description: "Infinite streams, lazy-map, lazy-filter, fibonacci",
        source: include_str!("../../sw-cor24-macrolisp/demos/lazy.l24"),
        prelude: PreludeTier::Full,
        stack: StackSize::EightKb,
    },
    Demo {
        title: "Reduce",
        description: "reduce/fold patterns: sum, product, reverse, max, join",
        source: include_str!("../../sw-cor24-macrolisp/demos/reduce.l24"),
        prelude: PreludeTier::Full,
        stack: StackSize::ThreeKb,
    },
    Demo {
        title: "Threading Macros",
        description: "-> (thread-first) and ->> (thread-last) pipelines",
        source: include_str!("../../sw-cor24-macrolisp/demos/threading.l24"),
        prelude: PreludeTier::Full,
        stack: StackSize::ThreeKb,
    },
    Demo {
        title: "Utility Functions",
        description: "partial, juxt, doseq, dotimes — Clojure-inspired",
        source: include_str!("../../sw-cor24-macrolisp/demos/utilities.l24"),
        prelude: PreludeTier::Full,
        stack: StackSize::ThreeKb,
    },
    // ── Scheme prelude ───────────────────────────────────────
    Demo {
        title: "Scheme Demo",
        description: "#t/#f, define-fn, let*, equal?, even?/odd?, factorial",
        source: include_str!("../../sw-cor24-macrolisp/demos/scheme.l24"),
        prelude: PreludeTier::Scheme,
        stack: StackSize::ThreeKb,
    },
];
